rm -rf build
rm -rf appimagetool-x86_64.AppImage
rm -rf linuxdeploy-plugin-qt-x86_64.AppImage
rm -rf linuxdeploy-x86_64.AppImage
rm -rf runtime-x86_64
rm -rf VIO_Localization_Server-x86_64.AppImage
rm -rf ./AppDir/usr/bin/*
rm -rf ./AppDir/usr/lib/*
rm -rf ./AppDir/usr/share/doc
rm -rf ./AppDir/usr/share/icons/hicolor/256x256/apps/*